name: WZTest
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs: 
  my_first_job:
    name: 第一个job
    runs-on: ubuntu-latest，ubuntu-18.04
    steps:
      - name: 打印一个pretting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: 赵四
          MIDDLE_NAME: The
          LAST_NAME: 本山
        run: 
         echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.  
  my_second_job:
    runs-on: ubuntu-latest，ubuntu-18.04
    needs: [my_first_job]
    steps:
      - name: 打印第二个内容
        env:
          MY_VAR: Hi there! My2name is
          FIRST_NAME: 赵四2
          MIDDLE_NAME: The2
          LAST_NAME: 本山2
        run: 
         echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME. 
    
      
  
